# The field registry: the single source of truth for every field a resource
# record may carry. Field grouping, type, cardinality, and which resource types
# a field applies to are declared here as metadata rather than as physical
# nesting, so that records stay flat and project cleanly to a rectangular view.

# Resource-type groupings used by `applies_to`.
.krt_organismish <- c("Experimental model: Cell line",
                      "Experimental model: Organism/strain",
                      "Biological sample", "Bacterial strain", "Viral vector")

# Construct one field spec.
.fld <- function(name, group, type = "string", cardinality = "one",
                 applies_to = "all", enum = NULL, help = "") {
  list(name = name, group = group, type = type, cardinality = cardinality,
       applies_to = applies_to, enum = enum,
       label_key = paste0("field.", name), help = help)
}

# Ordered field definitions. Order also drives column order in the wide view.
.krt_field_defs <- function() {
  list(
    ## identity
    .fld("resource_id", "identity", "string", help = "Stable within-table id."),
    .fld("resource_type", "identity", "enum",
         enum = "resource_type", help = "One of the 14 KRT resource types."),
    .fld("display_name", "identity", "string",
         help = "Name as it appears in the manuscript."),
    .fld("canonical_name", "identity", "string",
         help = "Authoritative or normalized name."),
    ## acquisition
    .fld("source_name", "acquisition", "string",
         help = "Vendor, repository, individual, or organization."),
    .fld("vendor", "acquisition", "string", help = "Commercial supplier."),
    .fld("catalog_number", "acquisition", "string", help = "Vendor catalog number."),
    .fld("lot_number", "acquisition", "string", help = "Lot number."),
    .fld("batch_number", "acquisition", "string", help = "Batch number."),
    ## identifiers (each a distinct typed field)
    .fld("rrid", "identifier", "string", help = "Research Resource Identifier."),
    .fld("doi", "identifier", "string", help = "Digital Object Identifier."),
    .fld("pmid", "identifier", "string", help = "PubMed identifier."),
    .fld("pmcid", "identifier", "string", help = "PubMed Central identifier."),
    .fld("accession", "identifier", "string", cardinality = "many",
         help = "Database accession(s), e.g. GEO, SRA, PDB, UniProt."),
    .fld("url", "identifier", "uri", help = "Persistent or landing-page URL."),
    ## version / state
    .fld("version", "version_state", "string",
         applies_to = c("Software/code", "Dataset", "Protocol"),
         help = "Version string, e.g. software or dataset version."),
    .fld("release_date", "version_state", "date", help = "Release or deposit date."),
    .fld("new_or_reuse", "version_state", "enum", enum = "new_or_reuse",
         help = "'new' if generated by the study, else 'reuse'."),
    .fld("status", "version_state", "enum", enum = "status",
         help = "Resource status."),
    ## biological qualification
    .fld("organism", "biological", "string", applies_to = .krt_organismish,
         help = "Species or organism."),
    .fld("taxon_id", "biological", "string", applies_to = .krt_organismish,
         help = "NCBI Taxonomy id."),
    .fld("strain", "biological", "string",
         applies_to = c("Experimental model: Organism/strain", "Bacterial strain"),
         help = "Strain designation."),
    .fld("genotype", "biological", "string", applies_to = .krt_organismish,
         help = "Genotype."),
    .fld("cellosaurus_id", "biological", "string",
         applies_to = "Experimental model: Cell line",
         help = "Cellosaurus accession (CVCL_...)."),
    .fld("authentication_method", "biological", "string",
         applies_to = "Experimental model: Cell line",
         help = "Cell-line authentication method, e.g. STR."),
    .fld("authentication_date", "biological", "date",
         applies_to = "Experimental model: Cell line",
         help = "Date of authentication."),
    .fld("mycoplasma_status", "biological", "enum", enum = "mycoplasma",
         applies_to = "Experimental model: Cell line",
         help = "Mycoplasma test result."),
    .fld("antibody_clone", "biological", "string", applies_to = "Antibody",
         help = "Antibody clone designation."),
    .fld("antibody_host", "biological", "string", applies_to = "Antibody",
         help = "Host species of the antibody."),
    .fld("antibody_clonality", "biological", "enum", enum = "clonality",
         applies_to = "Antibody", help = "Monoclonal or polyclonal."),
    .fld("antibody_conjugate", "biological", "string", applies_to = "Antibody",
         help = "Conjugate or label."),
    .fld("target", "biological", "string",
         applies_to = c("Antibody", "Oligonucleotide", "Recombinant DNA"),
         help = "Molecular target."),
    ## software details
    .fld("repository_url", "software", "uri", applies_to = "Software/code",
         help = "Source-code repository URL."),
    .fld("commit_sha", "software", "string", applies_to = "Software/code",
         help = "Git commit SHA pinning the version."),
    .fld("container_digest", "software", "string", applies_to = "Software/code",
         help = "Container image digest."),
    .fld("language", "software", "string", applies_to = "Software/code",
         help = "Programming language."),
    .fld("license", "software", "string",
         applies_to = c("Software/code", "Dataset", "Protocol"),
         help = "License (SPDX id where possible)."),
    ## free text
    .fld("notes", "notes", "string",
         help = "Additional information for unambiguous identification.")
  )
}

# Build a name -> spec lookup once per session.
.krt_field_env <- new.env(parent = emptyenv())
.field_index <- function() {
  if (is.null(.krt_field_env$idx)) {
    defs <- .krt_field_defs()
    idx <- stats::setNames(defs, vapply(defs, function(f) f$name, character(1)))
    .krt_field_env$idx <- idx
    .krt_field_env$order <- names(idx)
  }
  .krt_field_env$idx
}

#' Key Resources Table field registry
#'
#' The field registry declares every field a resource record may carry, together
#' with its group, type, cardinality, and the resource types it applies to.
#'
#' @param name A field name.
#' @param resource_type A resource type (one of [krt_resource_types()]).
#' @return `all_fields()` returns a named list of field specifications;
#'   `field_spec()` returns one specification (or `NULL`); `fields_for_type()`
#'   returns the names of fields that apply to a resource type; `field_label()`
#'   returns a human-readable label.
#' @examples
#' str(field_spec("rrid"))
#' fields_for_type("Antibody")
#' @name field_registry
NULL

#' @rdname field_registry
#' @export
all_fields <- function() .field_index()

#' @rdname field_registry
#' @export
field_spec <- function(name) {
  idx <- .field_index()
  idx[[name]]
}

#' @rdname field_registry
#' @export
fields_for_type <- function(resource_type) {
  idx <- .field_index()
  keep <- vapply(idx, function(f) {
    identical(f$applies_to, "all") || resource_type %in% f$applies_to
  }, logical(1))
  names(idx)[keep]
}

#' @rdname field_registry
#' @param locale Optional locale (currently advisory; labels fall back to a
#'   title-cased field name).
#' @export
field_label <- function(name, locale = NULL) {
  spec <- field_spec(name)
  if (is.null(spec)) return(name)
  # Human-readable default: replace underscores, title-case first letter, then
  # pass through the translation domain so localized labels are used when
  # available.
  lbl <- gsub("_", " ", name)
  lbl <- paste0(toupper(substr(lbl, 1L, 1L)), substr(lbl, 2L, nchar(lbl)))
  tr(lbl)
}

#' Coerce a field value to its declared type.
#'
#' Light, non-destructive coercion used when building resource records. Enum
#' fields are lower/normalized where the vocabulary is lowercase; unknown enum
#' values are passed through unchanged (validation reports on them separately).
#'
#' @param name Field name.
#' @param value The value to coerce.
#' @return The coerced value.
#' @export
#' @examples
#' coerce_field("new_or_reuse", "NEW")
#' coerce_field("pmid", 12345)
coerce_field <- function(name, value) {
  if (is.null(value)) return(NULL)
  spec <- field_spec(name)
  if (is.null(spec)) return(value)
  switch(spec$type,
    logical = as.logical(value),
    integer = suppressWarnings(as.integer(value)),
    enum = .coerce_enum(name, value, spec$enum),
    # date, uri, string, list all stored as character (list stays a vector)
    as.character(value)
  )
}

#' @noRd
.coerce_enum <- function(name, value, enum_key) {
  v <- as.character(value)
  vocab <- tryCatch(krt_vocab(enum_key), error = function(e) NULL)
  if (is.null(vocab)) return(v)
  # Normalize case for lowercase vocabularies (new_or_reuse, status, ...).
  if (all(vocab == tolower(vocab))) v <- tolower(v)
  v
}
