# Provenance and packaging graph exports: W3C PROV-JSON, RO-Crate 1.1 JSON-LD,
# and (optionally) RDF/Turtle.

#' Export the provenance graph as PROV-JSON
#'
#' Serializes the table's recorded activities as a W3C PROV-JSON document: the
#' table is an entity, each recorded step is an activity associated with the
#' `krt` software agent and generating the table.
#'
#' @param x A [krt_tbl].
#' @param path Output path, or `NULL` to return the JSON string.
#' @return The JSON string, or the path (invisibly).
#' @export
#' @examples
#' cat(substr(as_prov_json(normalize_ids(krt_example)), 1, 40))
as_prov_json <- function(x, path = NULL) {
  stopifnot(is_krt(x))
  ent_id <- paste0("krt:table/", x$table_id)
  entity <- stats::setNames(
    list(list(`prov:type` = "krt:KeyResourcesTable", `krt:title` = x$title %||% "")),
    ent_id)
  agent <- list(`krt:agent/krt` = list(`prov:type` = "prov:SoftwareAgent",
                                       `krt:name` = "krt"))
  activity <- list(); assoc <- list(); informed <- list()
  aids <- character(0)
  for (i in seq_along(x$provenance)) {
    e <- x$provenance[[i]]
    aid <- sprintf("krt:activity/%d", i)
    aids <- c(aids, aid)
    act <- list(`prov:type` = e$activity %||% "activity",
                `prov:atTime` = e$timestamp %||% "")
    if (!is.null(e$params)) {
      act[["krt:params"]] <- paste(names(e$params), unlist(e$params),
                                   sep = "=", collapse = "; ")
    }
    activity[[aid]] <- act
    assoc[[sprintf("_:wa%d", i)]] <- list(`prov:activity` = aid,
                                          `prov:agent` = "krt:agent/krt")
    if (i > 1L) {
      informed[[sprintf("_:wib%d", i)]] <- list(`prov:informant` = aids[i - 1L],
                                                `prov:activity` = aid)
    }
  }
  # The table as it stands was generated by the most recent activity; earlier
  # steps are linked as a chain rather than all generating the same entity.
  gen <- if (length(aids)) {
    list(`_:gen` = list(`prov:entity` = ent_id,
                        `prov:activity` = aids[length(aids)]))
  } else list()
  doc <- list(
    prefix = list(krt = "https://choxos.github.io/krt/prov#",
                  prov = "http://www.w3.org/ns/prov#"),
    entity = entity, agent = agent)
  if (length(activity)) doc$activity <- activity
  if (length(assoc)) doc$wasAssociatedWith <- assoc
  if (length(informed)) doc$wasInformedBy <- informed
  if (length(gen)) doc$wasGeneratedBy <- gen

  json <- as.character(jsonlite::toJSON(doc, auto_unbox = TRUE, pretty = TRUE,
                                        null = "null"))
  if (is.null(path)) return(json)
  .write_utf8(json, path)
  invisible(path)
}

#' Export a KRT as an RO-Crate 1.1 metadata document
#'
#' Describes the table as an RO-Crate Dataset whose parts are its resources,
#' each carrying its name, type, and identifiers.
#'
#' @param x A [krt_tbl].
#' @param path Output path, or `NULL` to return the JSON-LD string.
#' @return The JSON-LD string, or the path (invisibly).
#' @export
#' @examples
#' cat(substr(as_rocrate(krt_example), 1, 40))
as_rocrate <- function(x, path = NULL) {
  stopifnot(is_krt(x))
  parts <- lapply(x$resources, function(r) list(`@id` = paste0("#", r$resource_id)))
  # The root Dataset is the user's data; do not assert a license on it (its
  # license is the researcher's to choose). The GPL-3 license belongs to the
  # software that produced it.
  root <- list(`@id` = "./", `@type` = "Dataset",
               name = x$title %||% "Key Resources Table",
               description = "A Key Resources Table produced with the krt R package.",
               dateCreated = x$created_at, dateModified = x$updated_at)
  if (length(parts)) root$hasPart <- parts

  graph <- list(
    list(`@type` = "CreativeWork", `@id` = "ro-crate-metadata.json",
         conformsTo = list(`@id` = "https://w3id.org/ro/crate/1.1"),
         about = list(`@id` = "./")),
    root)
  for (r in x$resources) {
    ent <- compact(list(`@id` = paste0("#", r$resource_id), `@type` = "Thing",
                        name = r$display_name %||% r$resource_id,
                        additionalType = r$resource_type,
                        identifier = compose_identifier(r)))
    graph <- c(graph, list(ent))
  }
  graph <- c(graph, list(list(`@id` = "https://choxos.github.io/krt/",
                              `@type` = "SoftwareApplication", name = "krt",
                              license = list(`@id` = "https://spdx.org/licenses/GPL-3.0-only.html"))))
  doc <- list(`@context` = "https://w3id.org/ro/crate/1.1/context", `@graph` = graph)

  json <- as.character(jsonlite::toJSON(doc, auto_unbox = TRUE, pretty = TRUE))
  if (is.null(path)) return(json)
  .write_utf8(json, path)
  invisible(path)
}

#' Export a KRT as RDF (JSON-LD or Turtle)
#'
#' @param x A [krt_tbl].
#' @param format `"jsonld"` (default) or `"turtle"` (requires the `rdflib`
#'   package).
#' @param path Output path, or `NULL` to return the text.
#' @return The serialized RDF text, or the path (invisibly).
#' @export
#' @examples
#' invisible(as_rdf(krt_example, format = "jsonld"))
as_rdf <- function(x, format = c("jsonld", "turtle"), path = NULL) {
  stopifnot(is_krt(x))
  format <- match.arg(format)
  jsonld <- as_rocrate(x)
  if (identical(format, "jsonld")) {
    if (is.null(path)) return(jsonld)
    .write_utf8(jsonld, path)
    return(invisible(path))
  }
  need_pkg("rdflib", "RDF/Turtle serialization")
  # Build the graph directly (no JSON-LD dependency).
  rdf <- rdflib::rdf()
  RDF_TYPE <- "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
  DCT <- "http://purl.org/dc/terms/"
  SDO <- "http://schema.org/"
  KRT <- "https://choxos.github.io/krt/"
  subj <- paste0(KRT, "table/", x$table_id)
  rdflib::rdf_add(rdf, subj, RDF_TYPE, paste0(KRT, "KeyResourcesTable"), objectType = "uri")
  if (!is.null(x$title)) rdflib::rdf_add(rdf, subj, paste0(DCT, "title"), x$title)
  for (r in x$resources) {
    rs <- paste0(subj, "/", r$resource_id)
    rdflib::rdf_add(rdf, subj, paste0(DCT, "hasPart"), rs, objectType = "uri")
    rdflib::rdf_add(rdf, rs, paste0(SDO, "name"), r$display_name %||% r$resource_id)
    rdflib::rdf_add(rdf, rs, paste0(SDO, "additionalType"), r$resource_type %||% "")
    if (!is.null(r$rrid)) rdflib::rdf_add(rdf, rs, paste0(SDO, "identifier"), r$rrid)
    if (!is.null(r$doi)) rdflib::rdf_add(rdf, rs, paste0(SDO, "identifier"),
                                         paste0("https://doi.org/", r$doi))
  }
  out <- path %||% tempfile(fileext = ".ttl")
  rdflib::rdf_serialize(rdf, doc = out, format = "turtle")
  if (!is.null(path)) return(invisible(path))
  on.exit(unlink(out), add = TRUE)
  paste(readLines(out, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
}
